In [185]:
import pandas as pd
import numpy as np

In [186]:
data = pd.read_csv("./messy_sales - Sheet1.csv")

In [187]:
print(f"dataset has {data.shape[0]} rows and {data.shape[1]} columns")

dataset has 200 rows and 8 columns

# step 1 : Checking for INFO and Missing values

In [188]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Date               200 non-null    str
 1   Region             200 non-null    str
 2   Product            200 non-null    str
 3   Category           200 non-null    str
 4   Units Sold         196 non-null    str
 5   Unit Price         200 non-null    str
 6   Total Sales        197 non-null    str
 7   Profit Margin (%)  200 non-null    str
dtypes: str(8)
memory usage: 12.6 KB

### Handling Null values

In [189]:
data.isnull().sum()

Date                 0
Region               0
Product              0
Category             0
Units Sold           4
Unit Price           0
Total Sales          3
Profit Margin (%)    0
dtype: int64

In [190]:
data[data.isnull().any(axis=1)]

,Date,Region,Product,Category,Units Sold,Unit Price,Total Sales,Profit Margin (%)
2,2/13/2024,EAST,laptop,ELEC,NaN,489.12,NaN,0.08
10,January 26 2024,South,Desktop,ELEC,NaN,$100.76,NaN,0.08
19,1/8/2024,north,Laptop,ELEC,NaN,$169.86,NaN,0.08
38,2/26/2024,north,tablet,electronics,NaN,$443.40,"11,014",0.1

### before filling NANs , lets ensure our numeric column types are correct

In [191]:
print(data[["Units Sold", "Total Sales"]].dtypes)

data_str_to_int_mask = {"twenty": 20, "thirty": 30}

data["Units Sold"] = data["Units Sold"].replace(data_str_to_int_mask)

data["Units Sold"] = pd.to_numeric(data["Units Sold"], errors="coerce")
data["Total Sales"] = pd.to_numeric(data["Total Sales"], errors="coerce")

print("*" * 50)
print("Fixed!!!")
print("*" * 50)

print(data[["Units Sold", "Total Sales"]].dtypes)

Units Sold     str
Total Sales    str
dtype: object
**************************************************
Fixed!!!
**************************************************
Units Sold     float64
Total Sales    float64
dtype: object

### filling missing data with column mean

In [192]:
data["Units Sold"] = data["Units Sold"].fillna(round(data["Units Sold"].mean(), 2))

### filling missing data with 0

In [193]:
data["Total Sales"] = data["Total Sales"].fillna(0)

In [ ]:
data[["Units Sold", "Total Sales"]]

     Units Sold  Total Sales
0         32.00          0.0
1         72.00          0.0
2         34.23          0.0
3         30.00          0.0
4         47.00          0.0
..          ...          ...
195       20.00      23607.0
196       20.00          0.0
197       91.00          0.0
198       30.00      41246.0
199       20.00          0.0

[200 rows x 2 columns]

# step 2 : Clean Columns names

In [215]:
data.columns.to_list()

['Date',
 'Region',
 'Product',
 'Category',
 'Units Sold',
 'Unit Price',
 'Total Sales',
 'Profit Margin (%)']

In [212]:
# detect if and columns has extra spaces
columns_with_spaces = [col for col in data.columns if col.strip() != col]

In [217]:
# clean the stripes and rename column into lower
data.columns = data.columns.str.strip().str.lower().str.replace(" ", "_")

In [219]:
data.columns.to_list()

['date',
 'region',
 'product',
 'category',
 'units_sold',
 'unit_price',
 'total_sales',
 'profit_margin_(%)']

# step 3 : fix date formats